### ISSUE TITLE
Consider one more source for DNS history

### ISSUE THREAD

**Issue by Luci-d** [vincentcox/bypass-firewalls-like-cloudflare-by-dns-history#9]
Try out spyse.com for a historical DNS. Pretty similar to Securitytrails, but sometimes updates faster. Nevertheless sometimes is not, so better to use both I guess.

**Comment by vincentcox** [comment]
Hi there,
I'm a bit late to reply, but my intension is that if I find time somewhere in the future, I'll completely rewrite this into a python project. Same principle, less shitty bash code and more stability and DNS sources.

Unfortunately my life has been turned upside down the last months so I can't guarantee any ETA. The best way to help me on this is, is to make a list of DNS API's, their endpoints and how their results look like.
